// Authorization code
export const AUTHORIZATION_CODE_MISSING = 'AUTHORIZATION_CODE_MISSING';
export const AUTHORIZATION_CODE_ENDPOINT_ERROR = 'AUTHORIZATION_CODE_ENDPOINT_ERROR';
export const OAUTH_TOKENS_RETRIEVED = 'OAUTH_TOKENS_RETRIEVED';

// IDP
export const IDP_ENDPOINT_RETRIEVED = 'IDP_ENDPOINT_RETRIEVED';
export const IDP_ENDPOINT_RETRIEVAL_ERROR = 'IDP_ENDPOINT_RETRIEVAL_ERROR';
